CREATE TABLE IF NOT EXISTS results (
  url_hash VARCHAR(64) PRIMARY KEY,
  url TEXT NOT NULL,

  extension_count INT NOT NULL,
  authority_info_access BOOLEAN NOT NULL,
  authority_key_identifier BOOLEAN NOT NULL,
  subject_key_identifier BOOLEAN NOT NULL,
  basic_constraints BOOLEAN NOT NULL,
  certificate_policies BOOLEAN NOT NULL,
  extended_key_usage BOOLEAN NOT NULL,
  CRL_distribution_points BOOLEAN NOT NULL,
  freshest_CRL BOOLEAN NOT NULL,
  key_usage BOOLEAN NOT NULL,
  issuer_alt_name BOOLEAN NOT NULL,
  subject_alt_name BOOLEAN NOT NULL,
  subject_directory_attributes BOOLEAN NOT NULL,

  is_trusted_issuer BOOLEAN NOT NULL,
  is_prohibited_issuer BOOLEAN NOT NULL,
  is_prohibited_subject BOOLEAN NOT NULL,
  match_issuer_o_cn FLOAT NOT NULL,
  match_issuer_o_ou FLOAT NOT NULL,
  match_subject_o_cn FLOAT NOT NULL,
  match_subject_o_ou FLOAT NOT NULL,
  match_issuer_subject_cn FLOAT NOT NULL,
  match_website_issuer_cn FLOAT NOT NULL,
  match_website_altname FLOAT NOT NULL,
  match_website_subject_cn FLOAT NOT NULL,
  len_issuer_st INT NOT NULL,
  len_issuer_city INT NOT NULL,
  len_issuer_cn INT NOT NULL,
  len_issuer_o INT NOT NULL,
  len_issuer_ou INT NOT NULL,
  len_issuer_email INT NOT NULL,
  len_subject_st INT NOT NULL,
  len_subject_city INT NOT NULL,
  len_subject_cn INT NOT NULL,
  len_subject_o INT NOT NULL,
  len_subject_ou INT NOT NULL,
  len_subject_email INT NOT NULL,
  cert_issuer_c VARCHAR(20) NOT NULL,
  cert_subject_c VARCHAR(20) NOT NULL,

  diff_notbefore_timestamp INT NOT NULL,
  diff_notafter_timestamp INT NOT NULL,
  diff_notbefore_notafter INT NOT NULL,
  has_expired BOOLEAN NOT NULL,

  len_serialnum INT NOT NULL,
  signature_algorithm VARCHAR(100) NOT NULL,
  cert_version VARCHAR(20) NOT NULL,
  cert_count INT NOT NULL,
  has_certificate BOOLEAN NOT NULL
);


